//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoCondominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Condomino
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Condomino()
        {
            this.Reserva = new HashSet<Reserva>();
        }
    
        public int IDCondominio { get; set; }
        public string RG { get; set; }
        public Nullable<int> QTDChaves { get; set; }
        public string VagaGaragem { get; set; }
        public Nullable<int> IDPessoa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Reserva> Reserva { get; set; }

		public override string ToString()
		{
			return Pessoa.Nome;
		}
	}
}
