//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoCondominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reserva
    {
        public int IDReserva { get; set; }
        public string DSLocal { get; set; }
        public Nullable<System.DateTimeOffset> DTReservada { get; set; }
        public Nullable<int> IDCondomino { get; set; }
    
        public virtual Condomino Condomino { get; set; }

		public override string ToString()
		{
			return Condomino.Pessoa.Nome;
		}
	}
}
