//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjetoCondominio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Visitante
    {
        public int IDVisitante { get; set; }
        public Nullable<System.DateTimeOffset> DTVisitante { get; set; }
        public Nullable<int> IDPessoa { get; set; }
    
        public virtual Pessoa Pessoa { get; set; }

		public override string ToString()
		{
			return Pessoa.Nome;
		}
	}
}
